SELECT 
 DATE_SUB(DATE(data_inclusao), INTERVAL DAY(data_inclusao) - 1 DAY) AS PERIODO,
 SUM(CASE WHEN WORKFLOW_ADQUIRENTE LIKE 'MAQUINA INSTALADA C%' THEN 1 ELSE 0 END) AS MAQUINA_COM_FAT,
 SUM(CASE WHEN WORKFLOW_ADQUIRENTE LIKE 'MAQUINA INSTALADA S%' THEN 1 ELSE 0 END) AS MAQUINA_SEM_FAT,
 SUM(CASE WHEN WORKFLOW_ADQUIRENTE LIKE 'CLIENTE CREDENCIADO S%' THEN 1 ELSE 0 END) AS SEM_MAQUINA,
 SUM(CASE WHEN WORKFLOW_ADQUIRENTE LIKE 'EM ANALISE%' THEN 1 ELSE 0 END) AS EM_ANALISE,
 SUM(CASE WHEN WORKFLOW_ADQUIRENTE LIKE 'CADASTRO DECLINADO BIN%' THEN 1 ELSE 0 END) AS DECLINADO,
 SUM(CASE WHEN WORKFLOW_ADQUIRENTE LIKE 'REGRA%' THEN 1 ELSE 0 END) AS SEM_REGRA_EXPLICITA,
 SUM(CASE WHEN COALESCE(WORKFLOW_ADQUIRENTE, '') = '' THEN 1 ELSE 0 END) AS SEM_REGRA_VAZIO,
 COUNT(1) AS TOTAL

FROM Tbase_relatorio_clt
WHERE YEAR(data_inclusao) = YEAR(CURDATE())
GROUP BY MONTH(data_inclusao)