SELECT 
 SEGMENTO,
 SUM(CASE WHEN CLASSIFICACAO = 'A' THEN 1 ELSE 0 END) AS CLASSE_A,
 SUM(CASE WHEN CLASSIFICACAO = 'B' THEN 1 ELSE 0 END) AS CLASSE_B,
 SUM(CASE WHEN CLASSIFICACAO = 'C' THEN 1 ELSE 0 END) AS CLASSE_C,
 SUM(CASE WHEN CLASSIFICACAO = 'D' THEN 1 ELSE 0 END) AS CLASSE_D,
 SUM(CASE WHEN CLASSIFICACAO = 'NI' THEN 1 ELSE 0 END) AS CLASSE_NI,
 SUM(CASE WHEN CLASSIFICACAO = 'ND' THEN 1 ELSE 0 END) AS CLASSE_ND,
 COUNT(1) AS TOTAL,
 SUM(M1)  AS FATURAMENTO_M1,
 ROUND(AVG(M1),2)  AS TICKET_MEDIO

FROM Tbase_relatorio_clt
WHERE STATUS_CLIENTE = 'ATIVO'
GROUP BY SEGMENTO
ORDER BY COUNT(1) DESC